// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
namespace EnneagramMLNet
{
    public partial class PersonalityMLModel
    {
        /// <summary>
        /// model input class for PersonalityMLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(1)]
            [ColumnName(@"Q1")]
            [Description("Düzenli olarak yeni arkadaşlar edinirsiniz.")]
            public float Q1 { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Q2")]
            [Description("Boş zamanınızın çoğunu ilginizi çeken çeşitli konuları keşfederek harcıyorsunuz.")]
            public float Q2 { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Q3")]
            [Description("Başkalarının ağladığını görmek, kolaylıkla sizin de ağlamak istediğinizi hissetmenize neden olur.")]
            public float Q3 { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"Q4")]
            [Description("Çoğu zaman bir yedekleme planı için bir yedekleme planı yaparsınız..")]
            public float Q4 { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"Q5")]
            [Description("Çok fazla baskı altında bile genellikle sakin kalırsınız.")]
            public float Q5 { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"Q6")]
            [Description("Sosyal etkinliklerde nadiren yeni insanlarla tanıştırmaya çalışırsınız ve çoğunlukla zaten tanıdığınız kişilerle konuşursunuz.")]
            public float Q6 { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"Q7")]
            [Description("Bir projeyi diğerine başlamadan önce tamamen bitirmeyi tercih edersiniz.")]
            public float Q7 { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"Q8")]
            [Description("Çok duygusalsın.")]
            public float Q8 { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"Q9")]
            [Description("Programlar ve listeler gibi düzenleme araçlarını kullanmayı seviyorsunuz.")]
            public float Q9 { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"Q10")]
            [Description("Küçük bir hata bile genel yeteneklerinizden ve bilginizden şüphe etmenize neden olabilir.")]
            public float Q10 { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"Q11")]
            [Description("İlginç bulduğunuz birine doğru yürürken ve sohbet başlatırken kendinizi rahat hissedersiniz.")]
            public float Q11 { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"Q12")]
            [Description("Yaratıcı çalışmaların çeşitli yorumlarını ve analizlerini tartışmakla pek ilgilenmiyorsunuz.")]
            public float Q12 { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"Q13")]
            [Description("Kalbinizden ziyade kafanızı takip etmeye daha yatkınsınız.")]
            public float Q13 { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"Q14")]
            [Description("Belirli bir günlük rutini planlamak yerine genellikle herhangi bir anda ne hissediyorsanız onu yapmayı tercih edersiniz.")]
            public float Q14 { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"Q15")]
            [Description("Tanıştığınız insanlar üzerinde iyi bir izlenim bırakıp bırakmadığınız konusunda nadiren endişelenirsiniz.")]
            public float Q15 { get; set; }

            [LoadColumn(16)]
            [ColumnName(@"Q16")]
            [Description("Grup etkinliklerine katılmaktan hoşlanırsınız.")]
            public float Q16 { get; set; }

            [LoadColumn(17)]
            [ColumnName(@"Q17")]
            [Description("Sonuna dair kendi yorumunuzu ortaya çıkarmanızı sağlayan kitapları ve filmleri seviyorsunuz.")]
            public float Q17 { get; set; }

            [LoadColumn(18)]
            [ColumnName(@"Q18")]
            [Description("Mutluluğunuz, kendi başarılarınızdan çok başkalarının bir şeyleri başarmasına yardımcı olmaktan gelir.")]
            public float Q18 { get; set; }

            [LoadColumn(19)]
            [ColumnName(@"Q19")]
            [Description("O kadar çok şeyle ilgileniyorsunuz ki, bir sonraki adımda ne deneyeceğinizi seçmekte zorlanıyorsunuz.")]
            public float Q19 { get; set; }

            [LoadColumn(20)]
            [ColumnName(@"Q20")]
            [Description("İşlerin daha da kötüye gideceğinden endişelenme eğilimindesiniz.")]
            public float Q20 { get; set; }

            [LoadColumn(21)]
            [ColumnName(@"Q21")]
            [Description("Grup ortamlarında liderlik rollerinden kaçınırsınız.")]
            public float Q21 { get; set; }

            [LoadColumn(22)]
            [ColumnName(@"Q22")]
            [Description("Sen kesinlikle sanatsal tipte bir insan değilsin.")]
            public float Q22 { get; set; }

            [LoadColumn(23)]
            [ColumnName(@"Q23")]
            [Description("İnsanlar rasyonelliğe daha fazla ve duygularına daha az güvenselerdi dünyanın daha iyi bir yer olacağını düşünüyorsunuz.")]
            public float Q23 { get; set; }

            [LoadColumn(24)]
            [ColumnName(@"Q24")]
            [Description("Rahatlamanıza izin vermeden önce ev işlerinizi yapmayı tercih edersiniz.")]
            public float Q24 { get; set; }

            [LoadColumn(25)]
            [ColumnName(@"Q25")]
            [Description("İnsanların tartışmasını izlemekten hoşlanırsınız.")]
            public float Q25 { get; set; }

            [LoadColumn(26)]
            [ColumnName(@"Q26")]
            [Description("Dikkatleri üzerinize çekmekten kaçınma eğilimindesiniz.")]
            public float Q26 { get; set; }

            [LoadColumn(27)]
            [ColumnName(@"Q27")]
            [Description("Ruh haliniz çok çabuk değişebilir.")]
            public float Q27 { get; set; }

            [LoadColumn(28)]
            [ColumnName(@"Q28")]
            [Description("Sizin kadar verimli olmayan insanlara karşı sabrınızı kaybedersiniz.")]
            public float Q28 { get; set; }

            [LoadColumn(29)]
            [ColumnName(@"Q29")]
            [Description("Çoğu zaman işleri mümkün olan en son anda yaparsınız.")]
            public float Q29 { get; set; }

            [LoadColumn(30)]
            [ColumnName(@"Q30")]
            [Description("Ölümden sonra ne olacağı sorusu her zaman ilginizi çekmiştir.")]
            public float Q30 { get; set; }

            [LoadColumn(31)]
            [ColumnName(@"Q31")]
            [Description("Genellikle kendi başınıza olmaktansa başkalarının yanında olmayı tercih edersiniz.")]
            public float Q31 { get; set; }

            [LoadColumn(32)]
            [ColumnName(@"Q32")]
            [Description("Tartışma oldukça teorik hale geldiğinde sıkılırsınız veya ilginizi kaybedersiniz.")]
            public float Q32 { get; set; }

            [LoadColumn(33)]
            [ColumnName(@"Q33")]
            [Description("Deneyimleri sizinkinden çok farklı olan biriyle empati kurmayı kolay buluyorsunuz.")]
            public float Q33 { get; set; }

            [LoadColumn(34)]
            [ColumnName(@"Q34")]
            [Description("Genellikle nihai kararları mümkün olduğu kadar uzun süre ertelersiniz.")]
            public float Q34 { get; set; }

            [LoadColumn(35)]
            [ColumnName(@"Q35")]
            [Description("Yaptığınız seçimleri nadiren ikinci kez tahmin edersiniz.")]
            public float Q35 { get; set; }

            [LoadColumn(36)]
            [ColumnName(@"Q36")]
            [Description("Uzun ve yorucu bir haftanın ardından tam da ihtiyacınız olan şey canlı bir sosyal etkinlik.")]
            public float Q36 { get; set; }

            [LoadColumn(37)]
            [ColumnName(@"Q37")]
            [Description("Sanat müzelerine gitmekten hoşlanırsınız.")]
            public float Q37 { get; set; }

            [LoadColumn(38)]
            [ColumnName(@"Q38")]
            [Description("Çoğu zaman diğer insanların duygularını anlamakta zorluk çekersiniz.")]
            public float Q38 { get; set; }

            [LoadColumn(39)]
            [ColumnName(@"Q39")]
            [Description("Her gün için bir yapılacaklar listesine sahip olmayı seviyorsunuz.")]
            public float Q39 { get; set; }

            [LoadColumn(40)]
            [ColumnName(@"Q40")]
            [Description("Nadiren güvensiz hissedersiniz.")]
            public float Q40 { get; set; }

            [LoadColumn(41)]
            [ColumnName(@"Q41")]
            [Description("Telefon görüşmesi yapmaktan kaçınırsınız.")]
            public float Q41 { get; set; }

            [LoadColumn(42)]
            [ColumnName(@"Q42")]
            [Description("Kendinizden çok farklı görüşleri anlamaya çalışmak için sıklıkla çok zaman harcıyorsunuz.")]
            public float Q42 { get; set; }

            [LoadColumn(43)]
            [ColumnName(@"Q43")]
            [Description("Sosyal çevrenizde arkadaşlarınızla iletişim kuran ve faaliyetleri başlatan kişi genellikle sizsiniz.")]
            public float Q43 { get; set; }

            [LoadColumn(44)]
            [ColumnName(@"Q44")]
            [Description("Planlarınız kesintiye uğrarsa, en büyük önceliğiniz mümkün olan en kısa sürede yolunuza geri dönmektir.")]
            public float Q44 { get; set; }

            [LoadColumn(45)]
            [ColumnName(@"Q45")]
            [Description("Uzun zaman önce yaptığınız hatalardan hala rahatsızsınız.")]
            public float Q45 { get; set; }

            [LoadColumn(46)]
            [ColumnName(@"Q46")]
            [Description("İnsan varlığının nedenleri veya yaşamın anlamı üzerinde nadiren düşünürsünüz.")]
            public float Q46 { get; set; }

            [LoadColumn(47)]
            [ColumnName(@"Q47")]
            [Description("Duygularınız sizi, sizin onları kontrol ettiğinizden daha fazla kontrol eder.")]
            public float Q47 { get; set; }

            [LoadColumn(48)]
            [ColumnName(@"Q48")]
            [Description("Tamamen onların suçu olsa bile insanları kötü göstermemeye büyük özen gösteriyorsunuz.")]
            public float Q48 { get; set; }

            [LoadColumn(49)]
            [ColumnName(@"Q49")]
            [Description("Kişisel çalışma tarzınız, organize ve tutarlı çabalardan ziyade kendiliğinden enerji patlamalarına daha yakındır.")]
            public float Q49 { get; set; }

            [LoadColumn(50)]
            [ColumnName(@"Q50")]
            [Description("Birisi sizi çok iyi düşündüğünde, onun sizde hayal kırıklığı yaşamasının ne kadar süreceğini merak edersiniz.")]
            public float Q50 { get; set; }

            [LoadColumn(51)]
            [ColumnName(@"Q51")]
            [Description("Çoğu zaman yalnız çalışmanızı gerektiren bir işi seversiniz.")]
            public float Q51 { get; set; }

            [LoadColumn(52)]
            [ColumnName(@"Q52")]
            [Description("Soyut felsefi sorular üzerinde düşünmenin zaman kaybı olduğuna inanıyorsunuz.")]
            public float Q52 { get; set; }

            [LoadColumn(53)]
            [ColumnName(@"Q53")]
            [Description("Sessiz, samimi yerlerden ziyade yoğun, hareketli atmosferlere sahip yerlere çekildiğinizi hissedersiniz.")]
            public float Q53 { get; set; }

            [LoadColumn(54)]
            [ColumnName(@"Q54")]
            [Description("Birinin nasıl hissettiğini ilk bakışta anlarsınız.")]
            public float Q54 { get; set; }

            [LoadColumn(55)]
            [ColumnName(@"Q55")]
            [Description("Çoğu zaman kendinizi bunalmış hissedersiniz.")]
            public float Q55 { get; set; }

            [LoadColumn(56)]
            [ColumnName(@"Q56")]
            [Description("Hiçbir adımı atlamadan işleri metodik bir şekilde tamamlarsınız.")]
            public float Q56 { get; set; }

            [LoadColumn(57)]
            [ColumnName(@"Q57")]
            [Description("Tartışmalı olarak etiketlenen şeyler çok ilginizi çekiyor.")]
            public float Q57 { get; set; }

            [LoadColumn(58)]
            [ColumnName(@"Q58")]
            [Description("Başka birinin buna daha çok ihtiyacı olduğunu düşünürseniz, iyi bir fırsatı kaçırırsınız.")]
            public float Q58 { get; set; }

            [LoadColumn(59)]
            [ColumnName(@"Q59")]
            [Description("Son teslim tarihleriyle mücadele ediyorsunuz.")]
            public float Q59 { get; set; }

            [LoadColumn(60)]
            [ColumnName(@"Q60")]
            [Description("İşlerin sizin için yoluna gireceğine dair kendinize güveniyorsunuz.")]
            public float Q60 { get; set; }

            [LoadColumn(61)]
            [ColumnName(@"Personality")]
            public string Personality { get; set; }
            public string PredictionResult { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for PersonalityMLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Q1")]
            public float Q1 { get; set; }

            [ColumnName(@"Q2")]
            public float Q2 { get; set; }

            [ColumnName(@"Q3")]
            public float Q3 { get; set; }

            [ColumnName(@"Q4")]
            public float Q4 { get; set; }

            [ColumnName(@"Q5")]
            public float Q5 { get; set; }

            [ColumnName(@"Q6")]
            public float Q6 { get; set; }

            [ColumnName(@"Q7")]
            public float Q7 { get; set; }

            [ColumnName(@"Q8")]
            public float Q8 { get; set; }

            [ColumnName(@"Q9")]
            public float Q9 { get; set; }

            [ColumnName(@"Q10")]
            public float Q10 { get; set; }

            [ColumnName(@"Q11")]
            public float Q11 { get; set; }

            [ColumnName(@"Q12")]
            public float Q12 { get; set; }

            [ColumnName(@"Q13")]
            public float Q13 { get; set; }

            [ColumnName(@"Q14")]
            public float Q14 { get; set; }

            [ColumnName(@"Q15")]
            public float Q15 { get; set; }

            [ColumnName(@"Q16")]
            public float Q16 { get; set; }

            [ColumnName(@"Q17")]
            public float Q17 { get; set; }

            [ColumnName(@"Q18")]
            public float Q18 { get; set; }

            [ColumnName(@"Q19")]
            public float Q19 { get; set; }

            [ColumnName(@"Q20")]
            public float Q20 { get; set; }

            [ColumnName(@"Q21")]
            public float Q21 { get; set; }

            [ColumnName(@"Q22")]
            public float Q22 { get; set; }

            [ColumnName(@"Q23")]
            public float Q23 { get; set; }

            [ColumnName(@"Q24")]
            public float Q24 { get; set; }

            [ColumnName(@"Q25")]
            public float Q25 { get; set; }

            [ColumnName(@"Q26")]
            public float Q26 { get; set; }

            [ColumnName(@"Q27")]
            public float Q27 { get; set; }

            [ColumnName(@"Q28")]
            public float Q28 { get; set; }

            [ColumnName(@"Q29")]
            public float Q29 { get; set; }

            [ColumnName(@"Q30")]
            public float Q30 { get; set; }

            [ColumnName(@"Q31")]
            public float Q31 { get; set; }

            [ColumnName(@"Q32")]
            public float Q32 { get; set; }

            [ColumnName(@"Q33")]
            public float Q33 { get; set; }

            [ColumnName(@"Q34")]
            public float Q34 { get; set; }

            [ColumnName(@"Q35")]
            public float Q35 { get; set; }

            [ColumnName(@"Q36")]
            public float Q36 { get; set; }

            [ColumnName(@"Q37")]
            public float Q37 { get; set; }

            [ColumnName(@"Q38")]
            public float Q38 { get; set; }

            [ColumnName(@"Q39")]
            public float Q39 { get; set; }

            [ColumnName(@"Q40")]
            public float Q40 { get; set; }

            [ColumnName(@"Q41")]
            public float Q41 { get; set; }

            [ColumnName(@"Q42")]
            public float Q42 { get; set; }

            [ColumnName(@"Q43")]
            public float Q43 { get; set; }

            [ColumnName(@"Q44")]
            public float Q44 { get; set; }

            [ColumnName(@"Q45")]
            public float Q45 { get; set; }

            [ColumnName(@"Q46")]
            public float Q46 { get; set; }

            [ColumnName(@"Q47")]
            public float Q47 { get; set; }

            [ColumnName(@"Q48")]
            public float Q48 { get; set; }

            [ColumnName(@"Q49")]
            public float Q49 { get; set; }

            [ColumnName(@"Q50")]
            public float Q50 { get; set; }

            [ColumnName(@"Q51")]
            public float Q51 { get; set; }

            [ColumnName(@"Q52")]
            public float Q52 { get; set; }

            [ColumnName(@"Q53")]
            public float Q53 { get; set; }

            [ColumnName(@"Q54")]
            public float Q54 { get; set; }

            [ColumnName(@"Q55")]
            public float Q55 { get; set; }

            [ColumnName(@"Q56")]
            public float Q56 { get; set; }

            [ColumnName(@"Q57")]
            public float Q57 { get; set; }

            [ColumnName(@"Q58")]
            public float Q58 { get; set; }

            [ColumnName(@"Q59")]
            public float Q59 { get; set; }

            [ColumnName(@"Q60")]
            public float Q60 { get; set; }

            [ColumnName(@"Personality")]
            public uint Personality { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("PersonalityMLModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict scores for all possible labels.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static IOrderedEnumerable<KeyValuePair<string, float>> PredictAllLabels(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            var result = predEngine.Predict(input);
            return GetSortedScoresWithLabels(result);
        }

        /// <summary>
        /// Map the unlabeled result score array to the predicted label names.
        /// </summary>
        /// <param name="result">Prediction to get the labeled scores from.</param>
        /// <returns>Ordered list of label and score.</returns>
        /// <exception cref="Exception"></exception>
        public static IOrderedEnumerable<KeyValuePair<string, float>> GetSortedScoresWithLabels(ModelOutput result)
        {
            var unlabeledScores = result.Score;
            var labelNames = GetLabels(result);

            Dictionary<string, float> labledScores = new Dictionary<string, float>();
            for (int i = 0; i < labelNames.Count(); i++)
            {
                // Map the names to the predicted result score array
                var labelName = labelNames.ElementAt(i);
                labledScores.Add(labelName.ToString(), unlabeledScores[i]);
            }

            return labledScores.OrderByDescending(c => c.Value);
        }

        /// <summary>
        /// Get the ordered label names.
        /// </summary>
        /// <param name="result">Predicted result to get the labels from.</param>
        /// <returns>List of labels.</returns>
        /// <exception cref="Exception"></exception>
        private static IEnumerable<string> GetLabels(ModelOutput result)
        {
            var schema = PredictEngine.Value.OutputSchema;

            var labelColumn = schema.GetColumnOrNull("Personality");
            if (labelColumn == null)
            {
                throw new Exception("Personality column not found. Make sure the name searched for matches the name in the schema.");
            }

            // Key values contains an ordered array of the possible labels. This allows us to map the results to the correct label value.
            var keyNames = new VBuffer<ReadOnlyMemory<char>>();
            labelColumn.Value.GetKeyValues(ref keyNames);
            return keyNames.DenseValues().Select(x => x.ToString());
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

    }
}
